### ISSUE TITLE
Provide a logo

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/k8s-event-grid-bridge#28]
Provide a logo for this project.

This will be done by David Neal (@reverentgeek).

**Comment by khalidabuhakmeh** [comment]
![image](https://user-images.githubusercontent.com/228256/104192371-bb053500-53ec-11eb-83dc-03515197cc06.png)

[logos.zip](https://github.com/tomkerkhove/k8s-event-grid-bridge/files/5796151/logos.zip)
